### ISSUE TITLE
Should all the functions in sensor!() be pub?

### ISSUE THREAD

**Issue by Seppel3210** [pixix4/ev3dev-lang-rust#10]
When looking at the documentation for (the recently implemented) [IrSeekerSensor](https://docs.rs/ev3dev-lang-rust/0.9.6/ev3dev_lang_rust/sensors/struct.IrSeekerSensor.html) it looks really cluttered and you can just bypass the much nicer interface that is provided in the source file.

**Comment by pixix4** [comment]
One of the goals of this project is to provide direct bindings to the kernel drivers. Thus, the entire functionality of the driver should be mapped directly to Rust. Instead of the current sensor macro, this could be achieved with a sensor trait and a corresponding derive macro (So that you can import this functionality when you really need it). In fact, this was the original implementation of this library. This was changed after this [issue](https://github.com/pixix4/ev3dev-lang-rust/issues/3) (`rls` and `rust analizer` did not support custom derive macros for autocompletion and inline documentation).  I think that good editor support is important for a library (and especially one that may be used in education, as in my primary use case). I don't currently know if `rls` or `rust analizer` had an update to support this. If so, I would like to go back to the Derive macro because it is a more elegant solution. This would improve the stand-alone documentation, reduce the resulting binary size (due to less code duplication), and highlight the checked accessor functions of each sensor.

**Comment by pixix4** [comment]
I have refactored the sensor macro to a derive trait. You now need to manually import the `use ev3dev_lang_rust::sensor::Sensor` trait to access the low-level functions. The documentation for the sensor structures looks much cleaner now.
