### ISSUE TITLE
BrickPi

### ISSUE THREAD

**Issue by smessmer** [pixix4/ev3dev-lang-rust#11]
Thanks for this great library. The README mentions that this doesn't work with BrickPi. What's the reason it doesn't work and are you planning to add support?

**Comment by pixix4** [comment]
The BrickPi uses other conventions for port naming (see [ev3.py](https://github.com/ev3dev/ev3dev-lang-python/blob/ev3dev-stretch-1.x/ev3dev/ev3.py) vs [brick.py](https://github.com/ev3dev/ev3dev-lang-python/blob/ev3dev-stretch-1.x/ev3dev/brickpi.py)). Since I don't own a BrickPi, I can't test if a possible BrickPi compatible version works or not. If you have the possibility to test such an implementation, I can implement this in a new test branch.

**Comment by smessmer** [comment]
Ok makes sense. Thanks :)
I don't have a BrickPi yet but was thinking about buying one. I'll let you know if I do.

**Comment by pixix4** [comment]
Experimental support for BrickPI is now implemented. Since I could not test all functions, errors may occur. It can be enabled with:

```toml
[dependencies]
ev3dev_lang_rust = { version="0.13.0" default-features=false, features=["brickpi"] }
```
