### ISSUE TITLE
Make this lib more completion friendly

### ISSUE THREAD

**Issue by playest** [pixix4/ev3dev-lang-rust#3]
Hello,

I tried to use completion with this library and I had a rough time (here is a [summary](https://www.reddit.com/r/rust/comments/fpz47d/trying_to_make_completion_work_in_vscode_lead_me/) what I tried to do).

Did you manage to use completion with the library without macro expansion?

Thanks.

**Comment by pixix4** [comment]
Currently the code completion does not work. As you already figurer out, this is due to the use of `proc macros`. When creating the library I split the key functionality in traits to be as compatible as possible to the `ev3dev` specification and to reduce the code size. Until now I didn't know that this causes problems with code completion. 

Apart from waiting for the `rust-analyzer` project to support `proc marcos` ([PR](https://github.com/rust-analyzer/rust-analyzer/pull/3654)) it is possible to lift the functional traits (`TachoMotor`, `Sensor`, `Findable`) to classic macros. This will fix this issue for `rust-analyzer`. I will try to restructure the mentioned traits to solve this within the next few days.

**Comment by pixix4** [comment]
I created a branch [feature/improve-lsp-support](https://github.com/pixix4/ev3dev-lang-rust/tree/feature/improve-lsp-support) that removes most of the `proc macros` and some traits. With `rust-analyzer` the completion seems to work but for generated functions no inline doc is visible (it is generated for docs.rs but `rust-analyzer` and `clion` do not recognize this). 

Changes with this branch:

- Removed the traits  `Findable`, `Sensor`, `Motor`, `DcMotor`, `ServoMotor`,
  `TachoMotor`
- Added corresponding macros to generate the missing functionality
- Moved constants from module level to struct level to allow simpler imports (eg. `color_sensor::MODE_COL_REFLECT` -> `ColorSensor::MODE_COL_REFLECT`) 
- Removed the `prelude` module cause it is no longer necessary

You can try it locally and check if it brings improvements for you. I will do some test and try to fix the inline doc problem before merging.

**Comment by pixix4** [comment]
`rust-analyser` now supports inline documentation for macro-generated functions. So I think this issue can now be marked as solved.
