### ISSUE TITLE
Do you have the plan for Display part?This fuction is so good!

### ISSUE THREAD

**Issue by judemoses** [pixix4/ev3dev-lang-rust#4]
Think for you work,i like it very much

**Comment by pixix4** [comment]
The latest release (`v0.9.0`) now supports the framebuffer/screen. Since it has additional dependencies, it must be activated with the feature flag `screen`. The Python implementation of the screen class is based on the PIL library. There is no complete replacement for rust. Currently I use `image-rs`. This has similar image manipulation tools but unfortunately no drawing tools (like lines, rectangles, text...). If you know of an `image-rs` compatible drawing library, I would like to integrate it.

**Comment by pixix4** [comment]
It seems [`imageproc`](https://crates.io/crates/imageproc) can be used for drawing operations (like lines, rectangles, text, ...). This library works with an `image-rs` handle and does not need to be integrated.
